# Copyright (c) 2026 Lunar 24 contributors
# SPDX-License-Identifier: Apache-2.0
#
# Run at every build (cmake -P, from host/CMakeLists.txt): writes the build stamp shown in
# About Lunar 24 — the CI run number, the build time and the commit — to OUT. The file is
# rewritten only when the stamp changes, so an unchanged build recompiles nothing.
#
#   -DSRC=<repo root>  -DOUT=<build_info.h>
# The commit comes from LUNAR24_COMMIT when CI sets it (a pull request's own head commit, not
# the merge commit GitHub builds), else from git; the run number from GITHUB_RUN_NUMBER.

set(_commit "$ENV{LUNAR24_COMMIT}")
if(_commit STREQUAL "")
  execute_process(COMMAND git -C "${SRC}" rev-parse HEAD
                  OUTPUT_VARIABLE _commit OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
endif()
if(_commit STREQUAL "")
  set(_commit "unknown")
endif()
string(SUBSTRING "${_commit}" 0 7 _commit)

set(_run "$ENV{GITHUB_RUN_NUMBER}")
if(_run STREQUAL "")
  set(_run "local")
endif()

string(TIMESTAMP _time "%Y-%m-%d %H:%M UTC" UTC)

set(_content "// Generated by host/build_info.cmake at build time. Do not edit.\n#pragma once\n"
             "#define LUNAR24_BUILD_NUMBER \"${_run}\"\n"
             "#define LUNAR24_BUILD_TIME \"${_time}\"\n"
             "#define LUNAR24_BUILD_COMMIT \"${_commit}\"\n")
string(CONCAT _content ${_content})
set(_old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
  file(WRITE "${OUT}" "${_content}")
endif()
