// Copyright (c) 2026 Lunar 24 contributors
// SPDX-License-Identifier: Apache-2.0
//
// P5-② criterion 5 (task #33 → re-measure task #36, 裁决 0843a838): measured coords
// from the panel reference figure, and those measured coords must MATCH the figure —
// not merely be consistent with themselves. This is the "绝对锚" rule §5: an
// implementation that is consistently wrong still goes all green, so the path must be
// pinned to an EXTERNAL reference (the card-border / separated-column positions read
// off the reference figure), never to the rects themselves.
//
// WHY THE OLD CHECK WAS WRONG (the lesson 00-status §2k records): the previous
// criterion-5 validated each region's center against a "zone table" whose zone rects
// were co-authored with the region rects, and then a second round against an anchor
// set COPIED from the same numbers @Claude had measured. Two same-source quantities
// validating each other prove nothing — when the mixer was mislabelled to the bottom
// row, the wrong anchor agreed with the wrong rect and it stayed green.
//
// THE FIX (@Claude msg 9c660e3d): the anchor must be generated BY A MACHINE from the
// reference figure, never transcribed by a human. tools/measure_panel_regions.py reads
// design/reference/solar42N_panel_2400px.png, runs connected-components + divider
// detection, and emits BOTH generated/lunar24/panel_regions.json AND the C++ header
// generated/lunar24/panel_anchors.generated.h that THIS test includes. The test
// consumes that generated artifact — there are no hand-written anchor constants here.
// Two companion gates make the origin airtight:
//   (1) REGEN ZERO-DIFF — tools/measure_panel_regions.py --check must regenerate the
//       committed artifacts byte-identically, so the anchor set provably comes from
//       the image (a hand-edited anchor is a drift the gate catches).
//   (2) NEGATIVE — mutating a SINGLE GENERATED ANCHOR value (below) must make this
//       test go red, and a wrong/deviated region rect must too. Neither is vacuous.
//
// So: panel_regions rect (in panel_layout.h) → must converge on generated anchor →
// which must equal what the image produces. Neither @Pi nor @Claude transcribes an
// anchor value; the figure is the sole origin.

#include "mini_test.h"

#include <lunar24/core/panel_layout.h>
#include <lunar24/core/panel_transform.h>
#include <lunar24/panel_anchors.generated.h>

#include <cmath>
#include <cstdio>
#include <cstring>
#include <initializer_list>

namespace {
using namespace lunar24::core;
using lunar24::core::anchors::kAnchorCount;
using lunar24::core::anchors::kAnchors;
double near(double a, double b) { return std::fabs(a - b) < 1e-9; }

constexpr double kAnchorTol = 8.0;  // allow sub-pixel rounding; a >tol drift is a figure mismatch

bool anchor_by_site(const anchors::Anchor* arr, int n, const char* site, anchors::Anchor& out) {
  for (int i = 0; i < n; ++i) {
    if (std::strcmp(arr[i].site, site) == 0) { out = arr[i]; return true; }
  }
  return false;
}

bool asset_received(const anchors::Anchor* arr, int n, const char* site) {
  anchors::Anchor tmp;
  return anchor_by_site(arr, n, site, tmp);
}

// Index into the anchor array by site (the array's own ordering), mirroring
// panel_region_by_site for the region set. Used by the anchor-mutation negative so
// it edits the intended anchor regardless of how the anchor array is ordered.
int panel_anchor_by_site(const anchors::Anchor* arr, int n, const char* site) {
  for (int i = 0; i < n; ++i) {
    const char* a = arr[i].site;
    const char* b = site;
    bool same = true;
    while (*a && *b) { if (*a != *b) { same = false; break; } ++a; ++b; }
    if (same && *a == *b) return i;
  }
  return -1;
}

bool rect_near_anchor(const DesignRect& r, const anchors::Anchor& a) {
  return std::fabs(r.x0 - a.x0) <= kAnchorTol &&
         std::fabs(r.y0 - a.y0) <= kAnchorTol &&
         std::fabs(r.x1 - a.x1) <= kAnchorTol &&
         std::fabs(r.y1 - a.y1) <= kAnchorTol;
}
double rect_cx(const DesignRect& r) { return (r.x0 + r.x1) * 0.5; }
double rect_cy(const DesignRect& r) { return (r.y0 + r.y1) * 0.5; }

// A by-site lookup that works over a caller-supplied region set (for negatives on a
// mutated copy), mirroring panel_layout.h's panel_region_by_site semantics.
int panel_region_by_site_of(const PanelLayoutRegion* regs, int n, const char* site) {
  for (int i = 0; i < n; ++i) {
    const char* a = regs[i].site;
    const char* b = site;
    bool same = true;
    while (*a && *b) { if (*a != *b) { same = false; break; } ++a; ++b; }
    if (same && *a == *b) return i;
  }
  return -1;
}

// Full external-anchor convergence check over a region set (regs) against an EXPLICIT
// anchor array (arr,n). Parameterized so the same function validates the real anchors
// (must be TRUE) and a mutated-anchor copy or a mutated-region copy (must be FALSE).
// Returns true only if EVERY region has an anchor AND every anchor maps to a region
// that converges on it.
bool regions_anchor_ok(const PanelLayoutRegion* regs, int n,
                       const anchors::Anchor* arr, int nAnchors) {
  for (int i = 0; i < n; ++i)
    if (!asset_received(arr, nAnchors, regs[i].site)) { std::printf("  NO ANCHOR [%s]\n", regs[i].site); return false; }
  for (int a = 0; a < nAnchors; ++a) {
    const int r = panel_region_by_site_of(regs, n, arr[a].site);
    if (r < 0) { std::printf("  ANCHOR UNMEASURED [%s]\n", arr[a].site); return false; }
    if (!rect_near_anchor(regs[r].rect, arr[a])) {
      std::printf("  ANCHOR MISMATCH [%s] rect(%.0f,%.0f,%.0f,%.0f) vs anchor(%.0f,%.0f,%.0f,%.0f)\n",
                  arr[a].site,
                  regs[r].rect.x0, regs[r].rect.y0, regs[r].rect.x1, regs[r].rect.y1,
                  arr[a].x0, arr[a].y0, arr[a].x1, arr[a].y1);
      return false;
    }
  }
  return true;
}

int run(const char* suite) {
  // ---- (1) geometry sanity + label round-trip -------------------------------
  for (int i = 0; i < kPanelRegionCount; ++i) {
    const DesignRect& r = kPanelRegions[i].rect;
    CHECK(r.x0 < r.x1);
    CHECK(r.y0 < r.y1);
    CHECK(r.x0 >= kDesignArea.x0 && r.y0 >= kDesignArea.y0);
    CHECK(r.x1 <= kDesignArea.x1 && r.y1 <= kDesignArea.y1);
    CHECK_EQ(panel_region_by_site(kPanelRegions[i].site), i);
  }
  CHECK_EQ(panel_region_by_site("NO SUCH REGION"), -1);
  // measured region set == generated anchor set (no orphans either side)
  CHECK_EQ(kPanelRegionCount, kAnchorCount);
  {
    for (int a = 0; a < kAnchorCount; ++a) {
      const int r = panel_region_by_site(kAnchors[a].site);
      if (r < 0) std::printf("  ORPHAN ANCHOR [%s]\n", kAnchors[a].site);
      CHECK(r >= 0);
    }
    for (int i = 0; i < kPanelRegionCount; ++i) {
      anchors::Anchor tmp;
      if (!anchor_by_site(kAnchors, kAnchorCount, kPanelRegions[i].site, tmp))
        std::printf("  ORPHAN REGION [%s]\n", kPanelRegions[i].site);
      CHECK(anchor_by_site(kAnchors, kAnchorCount, kPanelRegions[i].site, tmp));
    }
  }
  // the by-array lookup helper and the by-label lookup agree on the real sets
  CHECK_EQ(panel_region_by_site_of(kPanelRegions, kPanelRegionCount, "中上 VCO A"),
           panel_region_by_site("中上 VCO A"));
  CHECK_EQ(panel_region_by_site_of(kPanelRegions, kPanelRegionCount, "中部 ENV B"),
           panel_region_by_site("中部 ENV B"));

  // ---- (2) EXTERNAL-ANCHOR convergence: the figure-anchored conflict check -----
  // The anchor array here is the GENERATED artifact, not a hand-written constant set.
  CHECK(regions_anchor_ok(kPanelRegions, kPanelRegionCount, kAnchors, kAnchorCount));

  // Same-band neighbours separated by a card gutter ("分离列" property) — independent
  // of the anchors: the mixer is a narrow strip between VCO A and VCO B, ENV A is left
  // of ENV B (the black ELTA-MUSIC credit card sits between them), and the bottom row
  // runs strictly left->right.
  {
    const int vcoA = panel_region_by_site("中上 VCO A");
    const int mix = panel_region_by_site("中部 VOICE MIXER");
    const int vcoB = panel_region_by_site("中上 VCO B");
    const int envA = panel_region_by_site("中部 ENV A");
    const int envB = panel_region_by_site("中部 ENV B");
    CHECK(vcoA >= 0 && mix >= 0 && vcoB >= 0 && envA >= 0 && envB >= 0);
    // 分离列: within the mid band, cards are separate (a beige gutter separates them).
    CHECK(kPanelRegions[vcoA].rect.x1 <= kPanelRegions[mix].rect.x0);  // VCO A | MIXER gutter
    CHECK(kPanelRegions[mix].rect.x1 <= kPanelRegions[vcoB].rect.x0);  // MIXER | VCO B gutter
    CHECK(kPanelRegions[envA].rect.x1 <= kPanelRegions[envB].rect.x0);  // ENV A | (credit) | ENV B
    // the mixer strip is narrow (part of the 535-706 band), NOT the full-height column.
    CHECK(kPanelRegions[mix].rect.y1 < kPanelRegions[vcoA].rect.y1);
  }
  {
    // bottom row strictly left->right, no overlap.
    const char* order[] = {"下排 LFO A", "下排 joystick", "下排 5-step seq",
                           "下排 preamp", "下排 env follower", "下排 LFO B"};
    int prev = panel_region_by_site(order[0]);
    CHECK(prev >= 0);
    for (int k = 1; k < 6; ++k) {
      const int cur = panel_region_by_site(order[k]);
      CHECK(cur >= 0);
      CHECK(kPanelRegions[prev].rect.x1 <= kPanelRegions[cur].rect.x0);  // no overlap
      CHECK(kPanelRegions[cur].rect.x0 - kPanelRegions[prev].rect.x1 >= 0);
      prev = cur;
    }
  }

  // ---- NEGATIVE 1: mutate ONE GENERATED ANCHOR value -> the convergence check must
  //      RED (@Claude: "改一个生成出来的 anchor 值 → 必须红"). This proves the check is
  //      sensitive to the anchor, not vacuous. We copy the generated anchors, shift the
  //      VOICE MIXER horizontally, and the region that used to converge now must not.
  {
    anchors::Anchor copy[kAnchorCount];
    std::memcpy(copy, kAnchors, sizeof copy);
    // Index into the ANCHOR array by its own site ordering (NOT a region-array index —
    // kAnchors and kPanelRegions are ordered differently, and mixing them mutates the
    // wrong anchor and lets the intended mixer edit slip through undetected).
    const int a = panel_anchor_by_site(kAnchors, kAnchorCount, "中部 VOICE MIXER");
    CHECK(a >= 0);
    copy[a].x0 += 40;  // the mixer anchor drifts off its card border
    CHECK_FALSE(regions_anchor_ok(kPanelRegions, kPanelRegionCount, copy, kAnchorCount));
  }

  // ---- NEGATIVES 2-5: the guard must also FIRE on wrong REGION rects ----
  {
    // (a) the OLD WRONG mixer value @Claude flagged ({416,880,1984,1035}) -> must red
    PanelLayoutRegion copy[kPanelRegionCount];
    std::memcpy(copy, kPanelRegions, sizeof copy);
    const int m = panel_region_by_site("中部 VOICE MIXER");
    CHECK(m >= 0);
    copy[m].rect = DesignRect{416, 880, 1984, 1035};  // the very mismatched value
    CHECK_FALSE(regions_anchor_ok(copy, kPanelRegionCount, kAnchors, kAnchorCount));
  }
  {
    // (b) a TRANSLATED rect (shift the mixer +40px) -> must red (the "整体平移" trapping)
    PanelLayoutRegion copy[kPanelRegionCount];
    std::memcpy(copy, kPanelRegions, sizeof copy);
    const int m = panel_region_by_site("中部 VOICE MIXER");
    copy[m].rect.x0 += 40;  // shift right, no longer on the card border
    CHECK_FALSE(regions_anchor_ok(copy, kPanelRegionCount, kAnchors, kAnchorCount));
  }
  {
    // (c) BOTTOM-ROW SWAP (joystick and 5-step rects exchanged) -> must red
    PanelLayoutRegion copy[kPanelRegionCount];
    std::memcpy(copy, kPanelRegions, sizeof copy);
    const int j = panel_region_by_site("下排 joystick");
    const int s = panel_region_by_site("下排 5-step seq");
    DesignRect t = copy[j].rect; copy[j].rect = copy[s].rect; copy[s].rect = t;
    CHECK_FALSE(regions_anchor_ok(copy, kPanelRegionCount, kAnchors, kAnchorCount));
  }
  {
    // (d) a region mislabelled to another SITE (rect under the wrong anchor) -> red
    PanelLayoutRegion copy[kPanelRegionCount];
    std::memcpy(copy, kPanelRegions, sizeof copy);
    const int d6 = panel_region_by_site("右中 DRONE 6");
    CHECK(d6 >= 0);
    copy[d6].site = "左上 DRONE 1";  // rect stays right-middle, label claims a left region
    CHECK_FALSE(regions_anchor_ok(copy, kPanelRegionCount, kAnchors, kAnchorCount));
  }

  // ---- (3) transform bridge on measured coords (criterion 1-4 are intact) -----
  for (int iz = 0; iz < kZoomScaleCount; ++iz) {
    const double ds = kZoomScales[iz];
    for (double ss : {1.0, 2.0}) {
      PanelTransform t = make_zoom_transform(ds, ss, 40.0, 25.0);
      CHECK(t.valid());
      for (int i = 0; i < kPanelRegionCount; ++i) {
        double bx, by, rx, ry;
        design_to_screen(t, rect_cx(kPanelRegions[i].rect), rect_cy(kPanelRegions[i].rect), bx, by);
        screen_to_design(t, bx, by, rx, ry);
        CHECK(near(rx, rect_cx(kPanelRegions[i].rect)));
        CHECK(near(ry, rect_cy(kPanelRegions[i].rect)));
      }
    }
  }

  // ---- (4) hit-testing uses the SAME transform (not a re-derived scale) -----
  const DesignRect cells[] = {
    DesignRect{50, 50, 400, 400},
    DesignRect{900, 50, 1500, 400},
    DesignRect{1900, 50, 2350, 400},
    DesignRect{50, 900, 500, 1300},
    DesignRect{1000, 900, 1600, 1300},
    DesignRect{1900, 900, 2350, 1300},
  };
  const int nCells = 6;
  for (int iz = 0; iz < kZoomScaleCount; ++iz) {
    const double ds = kZoomScales[iz];
    for (double ss : {1.0, 2.0, 1.5}) {
      PanelTransform t = make_zoom_transform(ds, ss, 10.0, 7.0);
      for (int c = 0; c < nCells; ++c) {
        double bx, by;
        design_to_screen(t, rect_cx(cells[c]), rect_cy(cells[c]), bx, by);
        const int hit = hit_test_rects(t, bx, by, cells, nCells);
        if (hit != c)
          std::printf("  HIT MISMATCH zoom=%.2f retina=%.1f cell=%d got=%d\n", ds, ss, c, hit);
        CHECK_EQ(hit, c);
      }
    }
  }

  return ::test::finish(suite);
}
}  // namespace

int main() {
  std::printf("== task #36 P5-2 criterion 5: measured panel region layout, MACHINE-generated anchors ==\n");
  return run("panel_layout");
}
