// Copyright (c) 2026 Lunar 24 contributors
// SPDX-License-Identifier: Apache-2.0
//
// task #109 (GH#19 S1): the SHARED windowed analytic BLAMP kernel.
//
// Several product oscillators have a SLOPE (first-derivative) discontinuity rather
// than a value jump, so the correct band-limiting tool for all of them is the same
// BLAMP kernel. This header is its single source of truth: it carries no oscillator
// state and is a pure function of (distance in samples, magnitude), so extracting it
// changes no caller's arithmetic -- it removes a second copy, it does not change a
// result. Both users are frozen to the SAME L=8 window:
//
//   * Vco::triangleBlampCorr   (VCO triangle: slope reversal at the peak/valley)
//   * SchmittOsc::railBlampCorr (Schmitt ramp: slope reversal at the rail clamp)
//
// Windowed analytic BLAMP residual (Esqueda, Valimaki & Bilbao, "Rounding Corners
// with BLAMP", Proc. DAFx-16, Brno, 2016).
//
// The triangle has first-derivative (slope) discontinuities at the peak (phase =
// integer, slope jumps -8) and valley (phase = half-integer, slope jumps +8).
// A BLAMP is the correct band-limiting kernel for a slope jump (it is the
// antiderivative of a BLEP). The ideal 2nd-integral kernel h(2) minus its trivial
// ramp gives the dimensionless residual R(u) (paper Eq.(6) form, U-sized), which
// is EVEN about the corner (R(-u)=R(u)) with R(0)=1/pi^2. We window it with an
// explicit C1 Hann window w(u)=cos^2(pi*u/(2L)) of support L=8 samples, so the
// CONTINUOUS kernel has both value AND first derivative -> 0 at the support edge.
// The scaled kernel g(u) = 8*R(u)*w(u) has corner 8/pi^2 (~0.810569469); per the
// paper (S4.1) it is scaled by 2*mu with mu = 4*|step|, so 2*mu = 8*|step|, encoded
// by calling the kernel with the per-sample distance and multiplying by mag = |step|.
//
// The kernel is evaluated by a LINEAR-INTERPOLATION look-up table (N=256 points over
// [0,L]), generated by tools/gen_gh19_blamp.py --L 8 --N 256. Consequently the FINAL
// discrete kernel is piecewise-linear (C0), only approximating the C1 continuous
// kernel; the residual at/beyond the support edge is exactly 0, but the LAST
// interpolation segment carries a small residual slope (~-6.9e-6) before dropping
// to 0 outside support -- a tiny, quantified discontinuity in slope (not a value
// jump). Pure function of (phase, step), no cross-block state, causal, no added
// latency. It is a truncated approximation, NOT the exact infinite-support kernel,
// and is labeled accordingly (no "no-droop"/"exact" claim).
//
// NOT a license to invent scale factors: each caller must derive its own mag from
// its OWN slope jump (the kernel carries the 8, not the caller's amplitude law).

#pragma once

#include <cmath>

namespace lunar24::core {

// Support radius L=8 samples and the table resolution N-1=255. The CONTINUOUS kernel
// is C1 at the boundary (value and slope -> 0); the table is linear-interpolated so
// the FINAL kernel is piecewise-linear (C0), not C1: the last interpolation segment
// has a small slope (~-6.9e-6) then 0 outside support -- a tiny slope discontinuity,
// not a value jump.
inline constexpr double kBlampSupport = 8.0;
inline constexpr int kN_blamp = 255;                 // [0,L] -> index [0,N-1].
inline constexpr double kBlampCorner = 0.810569469;  // 8/pi^2 == kBlampLut[0].

// Windowed analytic BLAMP residual table (g = 8*R*w). R = paper Eq.(6) minus the
// trivial ramp (dimensionless residual); w = C1 Hann window cos^2(pi*u/(2L));
// corner 8/pi^2 (~0.810569469). Generated by gen_gh19_blamp.py --L 8 --N 256 --cpp.
inline constexpr double kBlampLut[] = {
  0.810569469, 0.688989014, 0.575232564, 0.469285207, 0.371103333, 0.280615065, 0.197720873, 0.122294346,
  0.054183135, -0.006789959, -0.060825742, -0.108147254, -0.148998261, -0.183641643, -0.212357672, -0.235442196,
  -0.253204759, -0.265966646, -0.274058889, -0.277820230, -0.277595079, -0.273731452, -0.266578937, -0.256486668,
  -0.243801355, -0.228865354, -0.212014815, -0.193577899, -0.173873090, -0.153207613, -0.131875955, -0.110158512,
  -0.088320366, -0.066610190, -0.045259300, -0.024480853, -0.004469186, 0.014600688, 0.032573436, 0.049313607,
  0.064705692, 0.078654032, 0.091082585, 0.101934563, 0.111171924, 0.118774758, 0.124740543, 0.129083301,
  0.131832654, 0.133032794, 0.132741377, 0.131028346, 0.127974702, 0.123671236, 0.118217223, 0.111719098,
  0.104289125, 0.096044065, 0.087103866, 0.077590364, 0.067626032, 0.057332767, 0.046830727, 0.036237238,
  0.025665762, 0.015224945, 0.005017746, -0.004859346, -0.014317007, -0.023273678, -0.031656066, -0.039399548,
  -0.046448483, -0.052756414, -0.058286188, -0.063009969, -0.066909168, -0.069974282, -0.072204653, -0.073608145,
  -0.074200751, -0.074006135, -0.073055114, -0.071385084, -0.069039410, -0.066066764, -0.062520449, -0.058457692,
  -0.053938918, -0.049027029, -0.043786674, -0.038283530, -0.032583597, -0.026752515, -0.020854906, -0.014953750,
  -0.009109803, -0.003381048, 0.002177796, 0.007515721, 0.012585825, 0.017345646, 0.021757445, 0.025788425,
  0.029410899, 0.032602391, 0.035345686, 0.037628825, 0.039445037, 0.040792631, 0.041674832, 0.042099571,
  0.042079239, 0.041630395, 0.040773450, 0.039532312, 0.037934014, 0.036008318, 0.033787304, 0.031304954,
  0.028596723, 0.025699115, 0.022649258, 0.019484494, 0.016241974, 0.012958273, 0.009669023, 0.006408574,
  0.003209671, 0.000103168, -0.002882229, -0.005720191, -0.008386956, -0.010861489, -0.013125603, -0.015164049,
  -0.016964565, -0.018517901, -0.019817794, -0.020860933, -0.021646872, -0.022177930, -0.022459057, -0.022497676,
  -0.022303513, -0.021888390, -0.021266024, -0.020451795, -0.019462516, -0.018316188, -0.017031758, -0.015628869,
  -0.014127617, -0.012548311, -0.010911238, -0.009236440, -0.007543499, -0.005851343, -0.004178056, -0.002540716,
  -0.000955242, 0.000563730, 0.002002966, 0.003350711, 0.004596771, 0.005732549, 0.006751082, 0.007647041,
  0.008416725, 0.009058028, 0.009570392, 0.009954742, 0.010213410, 0.010350043, 0.010369498, 0.010277730,
  0.010081670, 0.009789102, 0.009408523, 0.008949014, 0.008420102, 0.007831626, 0.007193602, 0.006516095,
  0.005809096, 0.005082404, 0.004345515, 0.003607524, 0.002877033, 0.002162069, 0.001470017, 0.000807559,
  0.000180630, -0.000405617, -0.000946837, -0.001439500, -0.001880896, -0.002269121, -0.002603060, -0.002882355,
  -0.003107369, -0.003279138, -0.003399321, -0.003470142, -0.003494324, -0.003475028, -0.003415778, -0.003320399,
  -0.003192939, -0.003037601, -0.002858678, -0.002660483, -0.002447289, -0.002223268, -0.001992439, -0.001758617,
  -0.001525373, -0.001295993, -0.001073452, -0.000860383, -0.000659068, -0.000471418, -0.000298975, -0.000142908,
  -0.000004024, 0.000117222, 0.000220709, 0.000306625, 0.000375447, 0.000427907, 0.000464963, 0.000487761,
  0.000497606, 0.000495920, 0.000484211, 0.000464032, 0.000436952, 0.000404521, 0.000368238, 0.000329526,
  0.000289706, 0.000249976, 0.000211391, 0.000174854, 0.000141100, 0.000110695, 0.000084032, 0.000061333,
  0.000042653, 0.000027892, 0.000016807, 0.000009024, 0.000004059, 0.000001338, 0.000000216, 0.000000000,
};

// g(u): the windowed kernel at |u| in samples. Even; g(0) = 8/pi^2; exactly 0 for
// |u| >= L. NaN/0 map to the corner value (unchanged from before the extraction).
inline double blampKernel(double u) {
  const double a = std::fabs(u);
  if (!(a > 0.0)) return kBlampLut[0];          // u=0/NaN -> corner 8/pi^2.
  if (a >= 8) return 0.0;                       // windowed -> exactly 0 outside support.
  // The literal 8 below is the mandated L and is DELIBERATELY spelled out: it is what
  // tools/gen_gh19_blamp.py --check-prod derives L from, and that derivation must stay
  // an independent cross-check (against the KNOWN mandate) rather than read back a
  // symbol it is supposed to be validating. The static_assert keeps the literal and
  // the named constant from drifting apart.
  static_assert(kBlampSupport == 8.0, "check-prod derives L from the literal 8");
  const double tk = a / 8 * kN_blamp;
  const int i = static_cast<int>(tk);
  const double fr = tk - (double)i;
  return kBlampLut[i] * (1.0 - fr) + kBlampLut[i + 1] * fr;
}

// True when the support radius has reached half a period, i.e. when the peak and
// valley corners merge and the phase-local corner model is no longer verifiable.
// `stepCycles` is the caller's per-sample phase increment in cycles. Both callers
// reach the SAME physical predicate because each passes its own increment:
//   VCO triangle : step = dt      -> 8*dt >= 0.5
//   Schmitt ramp : step = 0.5*r   -> 8*(r/2) = 4r >= 0.5  <=> M = 1/r <= 8
// On this branch the caller must return the bounded naive waveform (NO correction)
// and list the range honestly (not as improved coverage).
inline bool blampSupportReachesHalfPeriod(double stepCycles) {
  return stepCycles * kBlampSupport >= 0.5;
}

}  // namespace lunar24::core
