#!/usr/bin/env python3
# Copyright (c) 2026 Lunar 24 contributors
# SPDX-License-Identifier: Apache-2.0
#
# build_gh19_blamp_candidates.py — reproducibly emit the isolated R&D vco.h VARIANTS
# for task #86 / GH#19 (windowed analytic BLAMP, "解析来源、Hann窗截断、线性插值 BLAMP 近似").
#
# It reads the COMMITTED production vco.h (the win8 integrated BLAMP) and produces, from
# that single source, all the variants the evidence runners need — so a clean checkout can
# regenerate every variant without depending on a gitignored build/ backup (@Codex 1a8ed7f2):
#   win4/win8  windowed analytic BLAMP (LUT via gen_gh19_blamp). win8 reproduces the
#              integrated production kernel and is the reproducible positive/reference.
#   naive      the SAME vco.h with the kTriangle correction DISABLED (pure triangle) —
#              the true uncorrected baseline ("显式去掉修正").
#   poly       the paper 4-point polynomial BLAMP (Esqueda §3 Table 1, corner 7/30,
#              single nearest peak+valley, support |u|<2) — the mandated counterexample.
#
# Outputs (kept in build/, gitignored, never shipped) — all renewable from committed source:
#   build/.vco_blamp_win4.h / win8.h / naive.h / poly.h
#
# Usage:
#   tools/build_gh19_blamp_candidates.py                 # all variants
#   tools/build_gh19_blamp_candidates.py --variant poly  # just the poly counterexample
import os, sys, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_gh19_blamp as G

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "core", "include", "lunar24", "core", "vco.h")
OUTDIR = os.path.join(ROOT, "build")

OLD_BLAMPG_START = "inline double Vco::blampG(double u) {"
OLD_CORR_START = "inline double Vco::triangleBlampCorr(double cp, double step) const {"


def blampg_body(L, N):
    # LUT over [0,L] even; returns C++ inline function.
    grid = [i * L / (N - 1) for i in range(N)]
    vals = [G.g(x, L) for x in grid]
    lines = []
    lines.append("// Windowed exact BLAMP residual LUT (g = 8*R*w). R = paper Eq.(6)-ramp,")
    lines.append("// dimensionless residual; w = C1 Hanning window cos^2(pi*u/(2L)); corner 8/pi^2.")
    lines.append(f"// Support radius L={L:g} samples; boundary value AND 1st derivative -> 0 (verified).")
    lines.append(f"// Generated by gen_gh19_blamp.py --L {L:g} --N {N} --cpp. Linear-interp error <=~1e-3.")
    lines.append("static constexpr double kLut[] = {")
    for i in range(0, N, 8):
        row = ", ".join(f"{v:.9f}" for v in vals[i:i + 8])
        lines.append(f"  {row},")
    lines.append("};")
    lines.append(f"static constexpr int kN_blamp = {N - 1};       // [0,L] -> index [0,N-1].")
    lines.append("const double a = std::fabs(u);")
    lines.append("if (!(a > 0.0)) return kLut[0];                 // u=0/NaN -> corner 8/pi^2.")
    lines.append(f"if (a >= {L:g}) return 0.0;                       // windowed -> exactly 0 outside support.")
    lines.append(f"const double tk = a / {L:g} * kN_blamp;")
    lines.append("const int i = static_cast<int>(tk);")
    lines.append("const double fr = tk - (double)i;")
    lines.append("return kLut[i] * (1.0 - fr) + kLut[i + 1] * fr;")
    return "\n".join(lines)


def corr_body(L):
    return f"""inline double Vco::triangleBlampCorr(double cp, double step) const {{
  const double dt = std::fabs(step);        // |instHz| / sr; finite on reversal.
  if (!(dt > 0.0) || !std::isfinite(dt)) return 0.0;  // zero/NaN step -> none.
  // Bounded high-step fallback: once the window radius reaches half a period,
  // the peak and valley corners merge and the phase-local corner model is no
  // longer verifiable. Return the bounded naive waveform (no correction), and
  // list this range honestly (not as improved coverage).
  if (dt * {L:g} >= 0.5) return 0.0;
  // Paper scale: residual scaled by 2*mu, with |mu| = 2*Tphi = 4*dt for the
  // +-1 triangle, so 2*mu = 8*dt. blampG already carries that 8 (corner 8/pi^2),
  // so the extra per-sample scale is dt: 2*mu * R = 8*dt * (1/pi^2) = dt*(8/pi^2).
  // (A naive 8*dt here would double-count the 8 and run 8x too large.)
  const double mag = dt;                    // per-sample scale; blampG peak = 8/pi^2.
  // Multi-wrap: sum ALL corners (peaks at integer phase, valleys at half-integer)
  // whose distance in samples from this sample is within the support L. The
  // previous code (single nearest peak + single nearest valley) missed corners
  // that a large step carries past a sample within the window. blampG is 0
  // outside L (windowed), so we only scan the whole periods that can touch it.
  const double frac = cp - std::floor(cp);  // phase within this period, in [0,1).
  const int radius = static_cast<int>(std::ceil({L:g} * dt)) + 1;
  double corr = 0.0;
  for (int n = -radius; n <= radius; ++n) {{
    double d = std::fabs((double)n - frac) / dt;      // peak at integer+n phase.
    if (d <= {L:g}) corr -= mag * blampG(d);          // -8 slope jump -> negative.
    d = std::fabs((double)n + 0.5 - frac) / dt;       // valley at half-integer+n.
    if (d <= {L:g}) corr += mag * blampG(d);          // +8 slope jump -> positive.
  }}
  return corr;
}}"""


def replace_function(src, sig, new_text):
    # Replace the function DEFINITION starting at `sig` with `new_text`, matching
    # braces to the function's own closing '}' so trailing content (the closing
    # `}  // namespace lunar24::core`) is preserved. `new_text` is the FULL
    # function text (signature through the closing brace).
    i0 = src.index(sig)
    open_i = src.index("{", i0)
    depth = 0
    j = open_i
    while j < len(src):
        c = src[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                close_i = j
                break
        j += 1
    else:
        raise SystemExit(f"brace mismatch replacing {sig[:50]!r}")
    return src[:i0] + new_text + src[close_i + 1:]


def build(L, N):
    src = open(SRC, encoding="utf-8").read()
    new_blampg = f"inline double Vco::blampG(double u) {{\n{blampg_body(L, N)}\n}}\n"
    new_corr = corr_body(L) + "\n"
    # Replace blampG then corr independently (each matched to its own closing '}').
    out = replace_function(src, OLD_BLAMPG_START, new_blampg)
    out = replace_function(out, OLD_CORR_START, new_corr)
    os.makedirs(OUTDIR, exist_ok=True)
    dst = os.path.join(OUTDIR, f".vco_blamp_win{L:g}.h")
    with open(dst, "w", encoding="utf-8") as f:
        f.write(out)
    # sanity: the new blampG must define kLut and the corr must loop over n.
    assert "kLut[]" in out, "blampG LUT missing"
    assert "for (int n = -radius" in out, "multi-wrap loop missing"
    # the namespace close must still be present (tail preserved).
    assert "}  // namespace lunar24::core" in out, "namespace close lost"
    o, c = out.count("{"), out.count("}")
    assert o == c, f"brace imbalance: open={o} close={c}"
    print(f"wrote {dst}  (blampG LUT N={N}, L={L:g}, multi-wrap loop; namespace close preserved)")
    return dst


# Reproducible NAIVE: the committed vco.h with the kTriangle correction DISABLED.
# The line below is the sole product-reachable call site of the corrector; replacing it
# with a comment leaves the triangle rendered pure (no correction) — the true baseline
# the ">=6 dB" rule must RED against. Keep it as a single anchored splice.
NAIVE_ANCHOR = "    *out += triangleBlampCorr(cumPitch_, step);"
NAIVE_REPL = "    // NAIVE: correction disabled (pure triangle) — reproducible naive baseline."


# Reproducible POLY: the paper 4-point polynomial BLAMP (Esqueda §3 Table 1, corner 7/30).
# It is a piecewise polynomial with support |u|<2 and a SINGLE nearest peak + nearest
# valley (it does not multi-wrap); the scale is 2µ with µ=4*step -> mag=8*dt, because the
# poly kernel does NOT already carry the 8 (its corner is 7/30, not 8/pi^2). This is the
# mandated counterexample: measured to be WORSE than naive in every cell (imp<0), 0/24 RED.
POLY_BLAMPG = """inline double Vco::blampG(double u) {
  const double a = std::fabs(u);
  if (!(a > 0.0)) return 7.0 / 30.0;            // u=0 (or NaN) -> corner peak.
  if (a >= 2.0) return 0.0;                      // outside support -> exactly 0.
  if (a < 1.0) {
    // span [0,T] (Table 1, row 3):  s^5/40 - s^4/12 + s^2/3 - s/2 + 7/30
    const double s = a;
    const double s2 = s * s, s3 = s2 * s, s4 = s3 * s, s5 = s4 * s;
    return s5 / 40.0 - s4 / 12.0 + s2 / 3.0 - s / 2.0 + 7.0 / 30.0;
  }
  // span [T,2T] (Table 1, row 4):  -s^5/120 + s^4/24 - s^3/12 + s^2/12 - s/24 + 1/120
  const double s = a - 1.0;
  const double s2 = s * s, s3 = s2 * s, s4 = s3 * s, s5 = s4 * s;
  return -s5 / 120.0 + s4 / 24.0 - s3 / 12.0 + s2 / 12.0 - s / 24.0 + 1.0 / 120.0;
}"""

POLY_CORR = """inline double Vco::triangleBlampCorr(double cp, double step) const {
  const double dt = std::fabs(step);         // |instHz| / sr; finite on reversal.
  if (!(dt > 0.0) || !std::isfinite(dt)) return 0.0;  // zero/NaN step -> none.
  // 2µ = 8*|step|: the slope-jump scale for the ±1 triangle (slope ±4 per phase).
  const double mag = 8.0 * dt;
  // Peak corner = integer phase (+1): a -8 slope jump, correction is NEGATIVE.
  const double uPeak = std::fabs(cp - std::round(cp)) / dt;
  // Valley corner = half-integer phase (-1): a +8 slope jump, correction is +.
  const double uVal = std::fabs(cp - (std::floor(cp) + 0.5)) / dt;
  double corr = 0.0;
  if (uPeak < 2.0) corr -= mag * blampG(uPeak);
  if (uVal < 2.0) corr += mag * blampG(uVal);  // both may be <2 for large/multi-wrap steps.
  return corr;
}"""


def build_naive():
    """Committed vco.h with the kTriangle correction disabled (true uncorrected baseline)."""
    src = open(SRC, encoding="utf-8").read()
    assert src.count(NAIVE_ANCHOR) == 1, "expect exactly 1 kTriangle corrector call"
    out = src.replace(NAIVE_ANCHOR, NAIVE_REPL)
    os.makedirs(OUTDIR, exist_ok=True)
    dst = os.path.join(OUTDIR, ".vco_blamp_naive.h")
    with open(dst, "w", encoding="utf-8") as f:
        f.write(out)
    o, c = out.count("{"), out.count("}")
    assert o == c, f"brace imbalance: open={o} close={c}"
    print(f"wrote {dst}  (kTriangle correction disabled -> pure triangle; corrector fn kept, unused)")
    return dst


def build_poly():
    """Committed vco.h with blampG + corr replaced by the paper 4-point polynomial BLAMP."""
    src = open(SRC, encoding="utf-8").read()
    out = replace_function(src, OLD_BLAMPG_START, POLY_BLAMPG + "\n")
    out = replace_function(out, OLD_CORR_START, POLY_CORR + "\n")
    os.makedirs(OUTDIR, exist_ok=True)
    dst = os.path.join(OUTDIR, ".vco_blamp_poly.h")
    with open(dst, "w", encoding="utf-8") as f:
        f.write(out)
    assert "7.0 / 30.0" in out, "poly blampG corner missing"
    assert "uPeak < 2.0" in out, "poly single-peak corr missing"
    assert "}  // namespace lunar24::core" in out, "namespace close lost"
    o, c = out.count("{"), out.count("}")
    assert o == c, f"brace imbalance: open={o} close={c}"
    print(f"wrote {dst}  (polyBLAMP kernel, corner 7/30, single nearest peak+valley, support |u|<2)")
    return dst


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--variant", action="append", choices=["win4", "win8", "naive", "poly"],
                    default=None, help="emit only these variants (default: all)")
    a = ap.parse_args()
    # Default to ALL so a clean checkout reproduces every variant the runners/CPU report need.
    want = set(a.variant) if a.variant else {"win4", "win8", "naive", "poly"}
    if "win4" in want:
        build(4, 256)
    if "win8" in want:
        build(8, 256)
    if "naive" in want:
        build_naive()
    if "poly" in want:
        build_poly()
