#!/usr/bin/env python3
# Copyright (c) 2026 Lunar 24 contributors
# SPDX-License-Identifier: Apache-2.0
#
# build_gh19_blamp_candidates.py — emit the two isolated R&D candidate vco.h
# variants for task #86 / GH#19 (windowed exact BLAMP, two support lengths).
#
# It loads the CURRENT (paper-faithful polyBLAMP) vco.h, replaces blampG with the
# windowed exact-residual LUT (g = 8*R*w, from gen_gh19_blamp) and replaces
# triangleBlampCorr with a MULTI-WRAP summation over ALL corners inside the support
# (previous code took only the single nearest peak+valley). A bounded high-step
# fallback (dt*L >= 0.5, i.e. corners of one period merge) returns the naive
# waveform honestly — documented, not counted as improved coverage.
#
# Outputs (kept in build/, gitignored, never shipped):
#   build/.vco_blamp_win4.h   (L = 4)
#   build/.vco_blamp_win8.h   (L = 8)
import os, sys, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_gh19_blamp as G

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "core", "include", "lunar24", "core", "vco.h")
OUTDIR = os.path.join(ROOT, "build")

OLD_BLAMPG_START = "inline double Vco::blampG(double u) {"
OLD_CORR_START = "inline double Vco::triangleBlampCorr(double cp, double step) const {"


def blampg_body(L, N):
    # LUT over [0,L] even; returns C++ inline function.
    grid = [i * L / (N - 1) for i in range(N)]
    vals = [G.g(x, L) for x in grid]
    lines = []
    lines.append("// Windowed exact BLAMP residual LUT (g = 8*R*w). R = paper Eq.(6)-ramp,")
    lines.append("// dimensionless residual; w = C1 Hanning window cos^2(pi*u/(2L)); corner 8/pi^2.")
    lines.append(f"// Support radius L={L:g} samples; boundary value AND 1st derivative -> 0 (verified).")
    lines.append(f"// Generated by gen_gh19_blamp.py --L {L:g} --N {N} --cpp. Linear-interp error <=~1e-3.")
    lines.append("static constexpr double kLut[] = {")
    for i in range(0, N, 8):
        row = ", ".join(f"{v:.9f}" for v in vals[i:i + 8])
        lines.append(f"  {row},")
    lines.append("};")
    lines.append(f"static constexpr int kN_blamp = {N - 1};       // [0,L] -> index [0,N-1].")
    lines.append("const double a = std::fabs(u);")
    lines.append("if (!(a > 0.0)) return kLut[0];                 // u=0/NaN -> corner 8/pi^2.")
    lines.append(f"if (a >= {L:g}) return 0.0;                       // windowed -> exactly 0 outside support.")
    lines.append(f"const double tk = a / {L:g} * kN_blamp;")
    lines.append("const int i = static_cast<int>(tk);")
    lines.append("const double fr = tk - (double)i;")
    lines.append("return kLut[i] * (1.0 - fr) + kLut[i + 1] * fr;")
    return "\n".join(lines)


def corr_body(L):
    return f"""inline double Vco::triangleBlampCorr(double cp, double step) const {{
  const double dt = std::fabs(step);        // |instHz| / sr; finite on reversal.
  if (!(dt > 0.0) || !std::isfinite(dt)) return 0.0;  // zero/NaN step -> none.
  // Bounded high-step fallback: once the window radius reaches half a period,
  // the peak and valley corners merge and the phase-local corner model is no
  // longer verifiable. Return the bounded naive waveform (no correction), and
  // list this range honestly (not as improved coverage).
  if (dt * {L:g} >= 0.5) return 0.0;
  // Paper scale: residual scaled by 2*mu, with |mu| = 2*Tphi = 4*dt for the
  // +-1 triangle, so 2*mu = 8*dt. blampG already carries that 8 (corner 8/pi^2),
  // so the extra per-sample scale is dt: 2*mu * R = 8*dt * (1/pi^2) = dt*(8/pi^2).
  // (A naive 8*dt here would double-count the 8 and run 8x too large.)
  const double mag = dt;                    // per-sample scale; blampG peak = 8/pi^2.
  // Multi-wrap: sum ALL corners (peaks at integer phase, valleys at half-integer)
  // whose distance in samples from this sample is within the support L. The
  // previous code (single nearest peak + single nearest valley) missed corners
  // that a large step carries past a sample within the window. blampG is 0
  // outside L (windowed), so we only scan the whole periods that can touch it.
  const double frac = cp - std::floor(cp);  // phase within this period, in [0,1).
  const int radius = static_cast<int>(std::ceil({L:g} * dt)) + 1;
  double corr = 0.0;
  for (int n = -radius; n <= radius; ++n) {{
    double d = std::fabs((double)n - frac) / dt;      // peak at integer+n phase.
    if (d <= {L:g}) corr -= mag * blampG(d);          // -8 slope jump -> negative.
    d = std::fabs((double)n + 0.5 - frac) / dt;       // valley at half-integer+n.
    if (d <= {L:g}) corr += mag * blampG(d);          // +8 slope jump -> positive.
  }}
  return corr;
}}"""


def replace_function(src, sig, new_text):
    # Replace the function DEFINITION starting at `sig` with `new_text`, matching
    # braces to the function's own closing '}' so trailing content (the closing
    # `}  // namespace lunar24::core`) is preserved. `new_text` is the FULL
    # function text (signature through the closing brace).
    i0 = src.index(sig)
    open_i = src.index("{", i0)
    depth = 0
    j = open_i
    while j < len(src):
        c = src[j]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                close_i = j
                break
        j += 1
    else:
        raise SystemExit(f"brace mismatch replacing {sig[:50]!r}")
    return src[:i0] + new_text + src[close_i + 1:]


def build(L, N):
    src = open(SRC, encoding="utf-8").read()
    new_blampg = f"inline double Vco::blampG(double u) {{\n{blampg_body(L, N)}\n}}\n"
    new_corr = corr_body(L) + "\n"
    # Replace blampG then corr independently (each matched to its own closing '}').
    out = replace_function(src, OLD_BLAMPG_START, new_blampg)
    out = replace_function(out, OLD_CORR_START, new_corr)
    os.makedirs(OUTDIR, exist_ok=True)
    dst = os.path.join(OUTDIR, f".vco_blamp_win{L:g}.h")
    with open(dst, "w", encoding="utf-8") as f:
        f.write(out)
    # sanity: the new blampG must define kLut and the corr must loop over n.
    assert "kLut[]" in out, "blampG LUT missing"
    assert "for (int n = -radius" in out, "multi-wrap loop missing"
    # the namespace close must still be present (tail preserved).
    assert "}  // namespace lunar24::core" in out, "namespace close lost"
    o, c = out.count("{"), out.count("}")
    assert o == c, f"brace imbalance: open={o} close={c}"
    print(f"wrote {dst}  (blampG LUT N={N}, L={L:g}, multi-wrap loop; namespace close preserved)")
    return dst


if __name__ == "__main__":
    # Two support lengths, same window + N, per @Codex "最多比较两种支撑长度".
    for L, N in [(4, 256), (8, 256)]:
        build(L, N)
