#!/usr/bin/env python3
# Copyright (c) 2026 Lunar 24 contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate host/include/host/panel_art.generated.h from the official Solar 42N panel PDF.

Extracts, in 2400 x 1552 panel units: the panel labels (position, size, colour,
orientation), the module frame outlines and the black title tabs. Brand marks
(SOLAR 42N, ELTA MUSIC, the "AMBIENT MACHINE" logotype, the Cyrillic name) are left
out; the app draws its own Lunar 24 name plate.

The PDF itself is third-party material and is not committed. Usage:
    pip install pymupdf
    python3 tools/gen_panel_art.py path/to/Solar42_panel.pdf
"""

import os
import sys

import pymupdf

OUT = os.path.join(os.path.dirname(__file__), "..", "host", "include", "host",
                   "panel_art.generated.h")
DROP_TEXT = {"POWER", "12V DC", "12V", "DC", "EXT.", "AUDIO", "EXT. AUDIO", "R", "L", "WET", "OUT", "WET OUT"}


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(pdf):
    doc = pymupdf.open(pdf)
    page = doc[0]
    z = 2400.0 / page.rect.width

    texts = []
    for block in page.get_text("dict")["blocks"]:
        for line in block.get("lines", []):
            dx, dy = line.get("dir", (1, 0))
            vertical = abs(dx) < 0.5
            for span in line["spans"]:
                t = span["text"].strip()
                if not t or span["font"].startswith("Magistral"):
                    continue  # brand logotypes
                x0, y0, x1, y1 = span["bbox"]
                cx, cy = (x0 + x1) / 2 * z, (y0 + y1) / 2 * z
                if cy < 120 and t in DROP_TEXT:
                    continue  # rear-panel connector labels (EXT AUDIO, WET OUT, POWER)
                t = t.encode("ascii", "ignore").decode()
                if not t:
                    continue
                texts.append((cx, cy, span["size"] * z, span["color"], vertical, t))

    frames, tabs = [], []
    for g in page.get_drawings():
        r = g["rect"]
        w, h = r.width * z, r.height * z
        fill, col = g.get("fill"), g.get("color")
        if g.get("type") == "s" and col and max(col) < 0.2 and w > 250 and h > 100:
            pts = []
            for it in g["items"]:
                if it[0] == "l":
                    pts += [it[1], it[2]]
                elif it[0] == "c":
                    p0, c1, c2, p3 = it[1], it[2], it[3], it[4]
                    for k in range(9):
                        t = k / 8.0
                        a = (1 - t) ** 3
                        b = 3 * (1 - t) ** 2 * t
                        c = 3 * (1 - t) * t * t
                        d = t ** 3
                        pts.append(pymupdf.Point(a * p0.x + b * c1.x + c * c2.x + d * p3.x,
                                                 a * p0.y + b * c1.y + c * c2.y + d * p3.y))
            if pts:
                frames.append([(p.x * z, p.y * z) for p in pts])
        x0, y0 = r.x0 * z, r.y0 * z
        glyph = 805 < y0 < 830 and (95 < x0 < 145 or 2065 < x0 < 2115)  # drone 3/6 antenna glyph
        logo = y0 < 235 and not (1100 < x0 < 1130)                      # brand letters (keep DUAL EFFECTOR tab)
        if fill and max(fill) < 0.15 and not glyph and not logo:
            if 40 < w and 12 < h < 60 and not (44 <= w <= 48 and 44 <= h <= 48):  # skip pan knob caps
                tabs.append((x0, y0, r.x1 * z, r.y1 * z))
            elif 14 < w < 45 and 40 < h < 400:
                tabs.append((x0, y0, r.x1 * z, r.y1 * z))
    tabs = sorted(set((round(a, 1), round(b, 1), round(c, 1), round(d, 1)) for a, b, c, d in tabs))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Copyright (c) 2026 Lunar 24 contributors\n// SPDX-License-Identifier: Apache-2.0\n//\n")
        f.write("// GENERATED by tools/gen_panel_art.py from the official Solar 42N panel drawing.\n")
        f.write("// Panel labels, module frames and title tabs in 2400 x 1552 panel units.\n\n")
        f.write("#pragma once\n\n#include <cstdint>\n\nnamespace lunar24::host::art {\n\n")
        f.write("struct Text { float x, y, size; std::uint32_t rgb; bool vertical; const char* text; };\n")
        f.write("struct Box { float x0, y0, x1, y1; };\n")
        f.write("struct Frame { std::uint32_t first, count; };\n\n")
        f.write("inline constexpr Text kTexts[] = {\n")
        for cx, cy, size, rgb, vert, t in texts:
            f.write(f"  {{{cx:.1f}f, {cy:.1f}f, {size:.1f}f, 0x{rgb:06x}u, {'true' if vert else 'false'}, {c_str(t)}}},\n")
        f.write("};\n\ninline constexpr Box kTabs[] = {\n")
        for a, b, c, d in tabs:
            f.write(f"  {{{a:.1f}f, {b:.1f}f, {c:.1f}f, {d:.1f}f}},\n")
        f.write("};\n\ninline constexpr float kFramePoints[] = {\n")
        index, first = [], 0
        for fr in frames:
            f.write("  " + ", ".join(f"{x:.1f}f, {y:.1f}f" for x, y in fr) + ",\n")
            index.append((first, len(fr)))
            first += len(fr)
        f.write("};\n\ninline constexpr Frame kFrames[] = {\n")
        for a, n in index:
            f.write(f"  {{{a}u, {n}u}},\n")
        f.write("};\n\n}  // namespace lunar24::host::art\n")
    print(f"wrote {OUT}: {len(texts)} texts, {len(tabs)} tabs, {len(frames)} frames")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
