#!/usr/bin/env python3
# Copyright (c) 2026 Lunar 24 contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate host/include/host/panel_logo.generated.h: the Lunar 24 name plates as outlines.

The name plates are set in Saira (SIL Open Font License 1.1, third_party/licenses/Saira-OFL.txt),
expanded width and semi-bold — a wide, rounded-square face in the spirit of the hardware's
logotype. The text is stored as flattened outlines, so the app needs no font file.

Usage:
    pip install fonttools
    curl -LO "https://raw.githubusercontent.com/google/fonts/main/ofl/saira/Saira%5Bwdth,wght%5D.ttf"
    python3 tools/gen_panel_logo.py "Saira[wdth,wght].ttf"
"""

import os
import sys

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

OUT = os.path.join(os.path.dirname(__file__), "..", "host", "include", "host",
                   "panel_logo.generated.h")
INK, RED = 0x0c0a0a, 0xc8202a
AXES = {"wdth": 125, "wght": 640}  # tuned by eye against the hardware logotype

# (text, colour, x, baseline y, cap height, width to spread the letters over or 0, align).
# x is the left edge ("l"), the centre ("c") or the right edge ("r"); None continues the line.
PLATES = [
    ("LUNAR", INK, 52, 234, 90, 0, "l"),
    ("24", RED, None, 234, 90, 0, "l"),          # main name plate, top left
    ("AMBIENT", INK, 1840, 180, 40, 342, "l"),
    ("MACHINE", INK, 1840, 229, 40, 342, "l"),   # top right, letter-spaced to one width
    ("24", RED, 1197, 824, 34, 0, "c"),
    ("LUNAR", INK, 1197, 851, 12, 74, "c"),      # between the envelopes (centre)
    ("LUNAR", INK, 1828, 1084, 19, 0, "l"),
    ("24", RED, None, 1084, 19, 0, "l"),         # above the keybed, right
]
WORD_GAP = 0.45  # space between runs on one line, in cap heights


def glyph_width(glyphs, name):
    from fontTools.pens.boundsPen import BoundsPen
    pen = BoundsPen(glyphs)
    glyphs[name].draw(pen)
    return pen.bounds[2] - pen.bounds[0] if pen.bounds else 0


class FlatPen(BasePen):
    def __init__(self, glyphset):
        super().__init__(glyphset)
        self.subs, self.cur = [], None

    def _moveTo(self, p):
        self.cur = [p]
        self.subs.append(self.cur)

    def _lineTo(self, p):
        self.cur.append(p)

    def _curveToOne(self, p1, p2, p3):
        p0 = self.cur[-1]
        for k in range(1, 7):
            t = k / 6
            a, b, c, d = (1 - t) ** 3, 3 * (1 - t) ** 2 * t, 3 * (1 - t) * t * t, t ** 3
            self.cur.append((a * p0[0] + b * p1[0] + c * p2[0] + d * p3[0], a * p0[1] + b * p1[1] + c * p2[1] + d * p3[1]))

    def _qCurveToOne(self, p1, p2):
        p0 = self.cur[-1]
        for k in range(1, 5):
            t = k / 4
            a, b, c = (1 - t) ** 2, 2 * (1 - t) * t, t * t
            self.cur.append((a * p0[0] + b * p1[0] + c * p2[0], a * p0[1] + b * p1[1] + c * p2[1]))

    def _closePath(self):
        self.cur = None


def main(font_path):
    font = instancer.instantiateVariableFont(TTFont(font_path), AXES)
    glyphs, cmap, hmtx = font.getGlyphSet(), font.getBestCmap(), font["hmtx"]
    cap = font["OS/2"].sCapHeight

    shapes, pts, subs = [], [], []
    line_end = {}
    for text, colour, x, base, cap_h, spread, align in PLATES:
        s = cap_h / cap
        names = [cmap[ord(ch)] for ch in text]
        advances = [hmtx[n][0] * s for n in names]
        if x is None:
            x = line_end[base] + WORD_GAP * cap_h
        ink = [(hmtx[n][1] * s, (hmtx[n][1] + glyph_width(glyphs, n)) * s) for n in names]  # ink x-range per glyph
        natural = sum(advances[:-1]) - ink[0][0] + ink[-1][1]
        track = (spread - natural) / (len(names) - 1) if spread and len(names) > 1 else 0.0
        width = spread or natural
        if align == "c":
            x -= width / 2
        elif align == "r":
            x -= width
        pen_x = x - hmtx[names[0]][1] * s  # start at the first glyph's ink
        first_sub = len(subs)
        for n, adv in zip(names, advances):
            pen = FlatPen(glyphs)
            glyphs[n].draw(pen)
            for sub in pen.subs:
                # TrueType: outer contours run clockwise, holes counter-clockwise (y up).
                signed = sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(sub, sub[1:] + sub[:1]))
                subs.append((len(pts), len(sub), signed > 0))
                pts.extend((pen_x + gx * s, base - gy * s) for gx, gy in sub)
            pen_x += adv + track
        line_end[base] = pen_x - track
        shapes.append((first_sub, len(subs) - first_sub, colour))

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Copyright (c) 2026 Lunar 24 contributors\n// SPDX-License-Identifier: Apache-2.0\n//\n")
        f.write("// GENERATED by tools/gen_panel_logo.py: the Lunar 24 name plates as outlines of the\n")
        f.write("// Saira font (SIL OFL 1.1, third_party/licenses/Saira-OFL.txt). Types: host/panel_art.h.\n\n")
        f.write("#pragma once\n\nnamespace lunar24::host::art {\n\n")
        f.write("inline constexpr float kLogoPoints[] = {\n")
        for i in range(0, len(pts), 8):
            f.write("  " + " ".join(f"{x:.1f}f, {y:.1f}f," for x, y in pts[i:i + 8]) + "\n")
        f.write("};\n\ninline constexpr SubPath kLogoSubPaths[] = {\n")
        for a, n, hole in subs:
            f.write(f"  {{{a}u, {n}u, true, {'true' if hole else 'false'}}},\n")
        f.write("};\n\ninline constexpr Shape kLogoShapes[] = {\n")
        for a, n, c in shapes:
            f.write(f"  {{{a}u, {n}u, 0x{c:06x}u, 0x000000u, 0.0f, kFill}},\n")
        f.write("};\n\n}  // namespace lunar24::host::art\n")
    print(f"wrote {OUT}: {len(shapes)} runs, {len(pts)} points")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
