#!/usr/bin/env python3
# Copyright (c) 2026 Lunar 24 contributors
# SPDX-License-Identifier: Apache-2.0
"""Generate host/include/host/ui_font.generated.h: the panel's label font, built into the app.

The app used to ask the OS for a system font by name ("Helvetica Neue" / "Segoe UI");
when that lookup fails IGraphics silently draws no text at all. Embedding the font makes
the labels identical on every machine. Noto Sans (SIL Open Font License 1.1,
third_party/licenses/NotoSans-OFL.txt) is a humanist sans close to the hardware's Lucida
Grande labels. Only the characters the panel uses are kept.

Usage:
    pip install fonttools
    curl -LO "https://raw.githubusercontent.com/google/fonts/main/ofl/notosans/NotoSans%5Bwdth,wght%5D.ttf"
    python3 tools/gen_ui_font.py "NotoSans[wdth,wght].ttf"
"""

import io
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

OUT = os.path.join(os.path.dirname(__file__), "..", "host", "include", "host", "ui_font.generated.h")
CHARS = [chr(c) for c in range(0x20, 0x7F)] + ["°", "±", "·", "–", "—", "•", "…"]
WEIGHTS = {"Regular": 400, "Bold": 700}


def build(path, weight):
    font = instancer.instantiateVariableFont(TTFont(path), {"wght": weight, "wdth": 100})
    opts = subset.Options()
    opts.layout_features = ["kern"]
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    sub = subset.Subsetter(opts)
    sub.populate(text="".join(CHARS))
    sub.subset(font)
    # Distinct names per weight: CoreText may otherwise treat both as the same font.
    style = "Bold" if weight >= 700 else "Regular"
    names = {1: "Noto Sans", 2: style, 4: f"Noto Sans {style}", 6: f"NotoSans-{style}",
             16: "Noto Sans", 17: style}
    table = font["name"]
    for rec in list(table.names):
        if rec.nameID in (3, 25) or rec.nameID in names:
            table.removeNames(nameID=rec.nameID)
    for nid, value in names.items():
        table.setName(value, nid, 3, 1, 0x409)
    # Supply the unique-ID record and remove unused variation metadata from this
    # static instance. This is font compatibility, not a text rasterization fix.
    table.setName(f"Noto Sans {style}", 3, 3, 1, 0x409)
    for tag in ("STAT", "fvar", "avar", "gvar", "HVAR", "MVAR", "cvar"):
        if tag in font:
            del font[tag]
    for rec in list(table.names):
        if rec.nameID >= 256:
            table.removeNames(nameID=rec.nameID)
    font["OS/2"].usWeightClass = weight
    font["OS/2"].fsSelection = (font["OS/2"].fsSelection & ~0x61) | (0x20 if style == "Bold" else 0x40)
    font["head"].macStyle = 1 if style == "Bold" else 0
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def main(path):
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// Copyright (c) 2026 Lunar 24 contributors\n// SPDX-License-Identifier: Apache-2.0\n//\n")
        f.write("// GENERATED by tools/gen_ui_font.py: Noto Sans Regular / Bold (SIL OFL 1.1,\n")
        f.write("// third_party/licenses/NotoSans-OFL.txt), subset to the panel's characters.\n\n")
        f.write("#pragma once\n\n#include <cstddef>\n\nnamespace lunar24::host::font {\n\n")
        for name, weight in WEIGHTS.items():
            data = build(path, weight)
            f.write(f"inline constexpr unsigned char k{name}[] = {{\n")
            for i in range(0, len(data), 20):
                f.write("  " + ", ".join(str(b) for b in data[i:i + 20]) + ",\n")
            f.write(f"}};\ninline constexpr std::size_t k{name}Size = sizeof(k{name});\n\n")
            print(f"{name}: {len(data)} bytes")
        f.write("}  // namespace lunar24::host::font\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
