#!/usr/bin/env python3
# Copyright (c) 2026 Lunar 24 contributors
# SPDX-License-Identifier: Apache-2.0
#
# GH#19 S6 PR-B (task #121) LEG 3: the MUTANT run -- the demonstration that the gate issues a NAMED
# RED, which LEG 2's refusal controls cannot show (a suite of refusals proves the gate can say no; it
# says nothing about whether it can say "this is worse").
#
# HOW IT ISOLATES THE MUTATION. Every arm is compiled HERE, from the same source file, by the same
# compiler, with the same flags on one link line, differing ONLY in which shadow include root is FIRST
# on the compile line. The roots are generated by tools/stage_gh19_prb_shadow.py, which refuses
# (non-zero exit, so this runner aborts INVALID) if an anchor does not occur exactly once or if the
# staged header is byte-identical to the tree's -- because a stale anchor would stage a PRISTINE header
# under the control arm's name, and the control would then measure the product against itself and
# "pass" while demonstrating nothing.
#
# THE ARMS
#   A  the tree probe, no shadow                      -- the corrected product
#   B  the probe with `improvement-bypass`            -- the neutralised product (two-edge correction
#                                                       returns 0)
#   C  the constructed-cell driver with `degen-dispatch` -- the PREMISE-LIVE arm (see below)
#   A2 the constructed-cell driver, no shadow         -- so C's refusal is not a permanently-firing alarm
#
# WHAT IT ASSERTS, AS TWO SEPARATELY-NAMED CLASSES (the criteria file's section 5)
#
#   IMPROVEMENT class -- the neutralised arm must be REJECTED BY NAME.
#     The two arms are analysed ONCE EACH and the gate is then run in two orientations over the SAME
#     two reports: acceptance (cand=A, neut=B) must PASS, and the mutant orientation (cand=B, neut=A)
#     must be RED with `PRB-FAIL-IMPROVEMENT` counted, ZERO refusals and no crash. Analysing each arm
#     once rather than twice is not a shortcut around the evidence -- it is what makes the two
#     orientations provably the same two measurements, and a refusal (exit 4, no judgement issued) or
#     a crash (no judgement issued either) is explicitly NOT counted as "the gate discriminated".
#
#   PREMISE-LIVE class -- the degenerate-dispatch arm demonstrates that the PREMISE CHECK IS LIVE, and
#     nothing about the identity. At `pwDepth_ == 0` the product's duty is `duty_ + 0.0 * cv`, which is
#     `duty_` EXACTLY in IEEE-754 on every sample, so the CV value is irrelevant BY ARITHMETIC. Dropping
#     the depth factor therefore lets the cable's value REACH the duty, which destroys the identity
#     criterion's own ANTECEDENT (the duty is no longer constant) rather than falsifying its consequent.
#     Reporting that as "the identity was broken" would report "the premise did not hold" as a
#     different fact about a different thing. What must be observed instead: the driver refuses with
#     its PREMISE exit bit and NOT its stimulus bit, the measured duty span is a number (not "it
#     failed"), and the PRISTINE driver of the same source exits 0 -- otherwise the bit would be a
#     permanently-firing alarm rather than a check.
#     The identity criterion's own falsifiability control is therefore a ONE-ULP TAMPER of the
#     constructed render, which is where it has to live: this runner re-renders every arm from source
#     on every run, so there is no point at which a tamper could be injected into a PIPELINE run. The
#     tamper is exercised against the gate's own inputs by LEG 2
#     (tools/gh19_prb_dynpwm_gate_negcontrol.py, control `degen_identity_one_ulp`), which requires
#     exactly `PRB-FAIL-DEGEN-IDENTITY` and requires the improvement columns NOT to move -- the S6
#     `gh19_s6_saw_baseline_report_pin` shape.
import argparse
import os
import platform
import shutil
import subprocess
import sys
import tempfile

PROBE_SRC = "tests/probes/gh19_s3_pulse_probe.cpp"
DEGEN_SRC = "tools/gh19_prb_degen_probe.cpp"
STAGER = "tools/stage_gh19_prb_shadow.py"

# The pinned R1 recipe. It is NOT duplicated as a JUDGED quantity: the analyzer derives `edge_eff` from
# these tap counts, the criteria pin `edge_eff_expected`, and the gate refuses BAND when they disagree.
# So a recipe that drifted from the pinned one REFUSES rather than silently judging a different band --
# which is why these may be repeated here without becoming a second, unchecked encoding.
TAPS = "2001"
TAPS2 = "4001"
DYNAMIC_CELLS = "56"
CONV_CELLS = "56"
DEGEN_PEAK_HI = "0.55"

EXIT_PASS = 0
EXIT_RED = 1
EXIT_REFUSE = 4

# The gate's machine-readable surface.
GATE_VERDICT = "PRB GATE verdict="
FAIL_IMPROVEMENT = "PRB-FAIL-IMPROVEMENT"


def sha256_of(path):
    import hashlib
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def criteria_values(path):
    """Every `criterion\\t<key>\\t<value>` row, as a dict. Read rather than re-typed, so the exit bits
    this runner asserts on are the ones the contract pins."""
    out = {}
    # encoding= is not optional: the platform default is the LOCALE codec (cp1252 on a Windows runner),
    # and these files carry non-ASCII characters in their prose.
    with open(path, "r", encoding="utf-8") as fh:
        for ln in fh:
            f = ln.rstrip("\n").split("\t")
            if len(f) == 3 and f[0] == "criterion":
                out[f[1]] = f[2]
    return out


def compile_cmd(repo_root, shadow_inc, src, out, compiler):
    """Mirrors the probe/degen targets' include sets (header-only INTERFACE libs, so the sources compile
    standalone). The shadow root MUST come first, so a mutated header wins over the tree's while every
    untouched header still resolves from core/include/generated."""
    cmd = [compiler, "-O3", "-DNDEBUG", "-std=c++17"]
    if sys.platform == "darwin":
        cmd += ["-arch", platform.machine() or "arm64"]
    cmd += ["-I", shadow_inc]
    cmd += ["-I", os.path.join(repo_root, "core/include"),
            "-I", os.path.join(repo_root, "generated"),
            "-I", os.path.join(repo_root, "tests/host"),
            "-I", os.path.join(repo_root, "host/include")]
    cmd += [os.path.join(repo_root, src), "-o", out]
    return cmd


def stage(repo_root, shadow_root, mutation):
    """Stage a shadow include root via the SAME tool the build uses. Returns (path, mutated_sha) or
    (None, None); the stager's own refusal message is echoed either way, because it names the anchor
    and the file, which is the whole diagnosis."""
    os.makedirs(shadow_root, exist_ok=True)
    p = subprocess.run([sys.executable, os.path.join(repo_root, STAGER),
                        "--repo-root", repo_root, "--out", shadow_root, "--mutation", mutation],
                       capture_output=True, text=True, encoding="utf-8")
    sys.stdout.write(p.stdout)
    if p.returncode != 0:
        sys.stderr.write(p.stderr)
        return None, None
    sha = None
    for ln in p.stdout.splitlines():
        if "mutated_sha256=" in ln:
            sha = ln.split("mutated_sha256=", 1)[1].split()[0]
    return os.path.join(shadow_root, "lunar24", "core",
                        "vco.h" if mutation == "degen-dispatch" else "pulse_blep_kernel.h"), sha


def run(cmd):
    return subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8")


def gate_facts(out):
    """The gate's own machine-readable surface: verdict, and the per-code counts.

    Counts are read rather than the individual detail lines, because the detail lines are suppressed
    past MAX_DETAIL -- so on a run that trips every cell, parsing the details would silently see only
    the first few and report a smaller number than the gate found.

    The line shapes are matched STRUCTURALLY (`<prefix> GATE verdict=...`, `<prefix> COUNT <BUCKET>
    <code> n=<count>`) and not against the literal "PRB": the prefixes are themselves criteria values
    (`gate_code_prefix` / `refuse_class_prefix` / `fail_class_prefix`), so a runner that keyed on the
    literals would report "the gate named nothing" if the vocabulary were ever changed in one place
    and not the other -- the exact drift this file exists to avoid.
    """
    facts = {"verdict": None, "fail": {}, "refuse": {}}
    for ln in out.splitlines():
        tok = ln.split()
        if len(tok) >= 3 and tok[1] == "GATE" and tok[2].startswith("verdict="):
            facts["verdict"] = tok[2].split("=", 1)[1]
        elif len(tok) >= 5 and tok[1] == "COUNT" and tok[2] in ("FAIL", "REFUSE"):
            try:
                n = int(tok[4].split("=", 1)[1])
            except (IndexError, ValueError):
                continue
            facts["fail" if tok[2] == "FAIL" else "refuse"][tok[3]] = n
    return facts


def main():
    ap = argparse.ArgumentParser(
        description="GH#19 S6 PR-B (task #121): the gate must issue a NAMED RED on the neutralised arm")
    ap.add_argument("--compiler", required=True, help="the C++ compiler CMake is using")
    ap.add_argument("--repo-root", default=".", help="repo root")
    ap.add_argument("--criteria", required=True)
    ap.add_argument("--analyzer", required=True, help="tools/gh19_s3_pulse_analyze.py")
    ap.add_argument("--gate", required=True, help="tools/gh19_prb_dynpwm_acceptance.py")
    ap.add_argument("--out", default=None, help="scratch dir (default: a tempdir, removed on exit)")
    args = ap.parse_args()

    root = args.repo_root
    crit = criteria_values(args.criteria)
    bit_stimulus = int(crit.get("degen_driver_stimulus_exit_bit", "5"))
    bit_premise = int(crit.get("degen_driver_premise_exit_bit", "6"))
    problems = []

    tmp = tempfile.mkdtemp(prefix="gh19prbmut-") if args.out is None else args.out
    try:
        if args.out is not None:
            os.makedirs(tmp, exist_ok=True)
        # An EMPTY include root for the pristine arms, so their compile line differs from the control
        # arms' in exactly one respect: which directory is searched first.
        pristine_inc = os.path.join(tmp, "inc_pristine")
        os.makedirs(pristine_inc, exist_ok=True)

        shadows = {}
        for mutation in ("improvement-bypass", "degen-dispatch"):
            path, sha = stage(root, os.path.join(tmp, "inc_" + mutation.replace("-", "_")), mutation)
            if path is None:
                print("INVALID: could not stage the %s shadow root" % mutation)
                return 2
            shadows[mutation] = (os.path.dirname(os.path.dirname(os.path.dirname(path))), sha)
            print("MUTANT shadow mutation=%s root=%s mutated_sha256=%s"
                  % (mutation, shadows[mutation][0], sha))

        # ---- compile every arm, and treat a compile error as INVALID rather than as a red ----------
        arms = (("probe_A", PROBE_SRC, pristine_inc),
                ("probe_B", PROBE_SRC, shadows["improvement-bypass"][0]),
                ("degen_A2", DEGEN_SRC, pristine_inc),
                ("degen_C", DEGEN_SRC, shadows["degen-dispatch"][0]))
        bins = {}
        for tag, src, inc in arms:
            out_bin = os.path.join(tmp, tag)
            b = run(compile_cmd(root, inc, src, out_bin, args.compiler))
            if b.returncode != 0:
                sys.stderr.write("INVALID: the %s arm did not compile -- a compile error is NOT a red, "
                                 "it says nothing about whether the gate can judge a working "
                                 "product:\n%s\n" % (tag, b.stderr[-2000:]))
                return 2
            bins[tag] = out_bin

        # ---- render ----------------------------------------------------------------------------------
        dirs = {}
        for tag in ("probe_A", "probe_B"):
            d = os.path.join(tmp, "arm_" + tag)
            os.makedirs(d, exist_ok=True)
            p = run([bins[tag], "--out", d])
            if p.returncode != 0:
                sys.stderr.write("INVALID: the %s render exited %d\n%s\n" % (tag, p.returncode, p.stderr))
                return 2
            dirs[tag] = d

        # The PRISTINE constructed-cell arm is what the gate reads for the identity. The degen-dispatch
        # arm is NEVER a gate input: it exists to show the premise check fires, and judging the identity
        # on an arm whose antecedent is gone is exactly the confusion this slice's criteria now name.
        dirs["degen_A2"] = os.path.join(tmp, "arm_degen_A2")
        os.makedirs(dirs["degen_A2"], exist_ok=True)
        p = run([bins["degen_A2"], "--out", dirs["degen_A2"], "--peak-hi", DEGEN_PEAK_HI])
        sys.stdout.write(p.stdout)
        print("MUTANT degen_pristine_exit=%d (must be 0: otherwise the premise bit below is a "
              "permanently-firing alarm rather than a check)" % p.returncode)
        if p.returncode != 0:
            sys.stderr.write(p.stderr)
            problems.append("the PRISTINE constructed-cell driver exited %d, so the control arm's "
                            "refusal below would prove nothing" % p.returncode)

        # ---- the PREMISE-LIVE arm ------------------------------------------------------------------
        dirs["degen_C"] = os.path.join(tmp, "arm_degen_C")
        os.makedirs(dirs["degen_C"], exist_ok=True)
        p = run([bins["degen_C"], "--out", dirs["degen_C"], "--peak-hi", DEGEN_PEAK_HI])
        sys.stdout.write(p.stdout)
        rc = p.returncode
        n_premise = p.stderr.count("FATAL-PREMISE")
        n_stimulus = p.stderr.count("FATAL-STIMULUS")
        spans = [ln.split("src_span=")[-1].split(",")[0].strip() for ln in p.stderr.splitlines()
                 if "FATAL-PREMISE" in ln and "src_span=" in ln]
        print("MUTANT degen_dispatch_exit=%d stimulus_bit=%s premise_bit=%s fatal_premise=%d "
              "fatal_stimulus=%d measured_src_span=%s"
              % (rc, bool(rc & (1 << bit_stimulus)), bool(rc & (1 << bit_premise)),
                 n_premise, n_stimulus, ",".join(spans) if spans else "-"))
        if not (rc & (1 << bit_premise)):
            problems.append("the degen-dispatch arm did not set the PREMISE bit (%d); exit=%d"
                            % (bit_premise, rc))
        if rc & (1 << bit_stimulus):
            problems.append("the degen-dispatch arm set the STIMULUS bit (%d): the two surfaces are "
                            "supposed to be separable, and a run reported under both names is not "
                            "evidence about either" % bit_stimulus)
        if n_premise < 1:
            problems.append("the degen-dispatch arm printed no FATAL-PREMISE line, so the premise "
                            "check's diagnostic was never reached")
        if n_stimulus != 0:
            problems.append("the degen-dispatch arm printed %d FATAL-STIMULUS line(s): the stimulus "
                            "did not fail and must not be reported as if it had" % n_stimulus)

        # ---- the two probe arms must declare the SAME plan ------------------------------------------
        # The mutation lives inside a header the plan does not describe, so the two arms are the same
        # experiment and a differing plan would mean they had stopped being one -- in which case the
        # orientation swap below would be swapping more than the pairing and the whole attribution would
        # be void. Reported either way, and the plan the gate is handed is the CAND arm's own, which is
        # what the pipeline does.
        plans = {}
        for tag in ("probe_A", "probe_B"):
            pp = os.path.join(dirs[tag], "gh19_s3_plan.tsv")
            plans[tag] = sha256_of(pp) if os.path.exists(pp) else None
        print("MUTANT plan_sha probe_A=%s probe_B=%s" % (plans["probe_A"], plans["probe_B"]))
        if plans["probe_A"] != plans["probe_B"]:
            problems.append("the two probe arms declare DIFFERENT plans (%s vs %s): the arms are no "
                            "longer the same experiment, so swapping their roles would swap more than "
                            "the cand/neut pairing" % (plans["probe_A"], plans["probe_B"]))

        # ---- analyse each arm ONCE, then judge in both orientations --------------------------------
        recipe = ["--align-check", "--self-check", "--taps", TAPS, "--taps2", TAPS2,
                  "--dynamic-cells", DYNAMIC_CELLS, "--conv-cells", CONV_CELLS]
        reports = {}
        for tag in ("probe_A", "probe_B"):
            rp = os.path.join(tmp, tag + "_report.txt")
            p = run([sys.executable, args.analyzer, "--arm", dirs[tag], "--label", tag] + recipe)
            if p.returncode != 0:
                sys.stderr.write("INVALID: the analyzer failed on %s (rc=%d)\n%s\n%s\n"
                                 % (tag, p.returncode, p.stdout[-2000:], p.stderr[-2000:]))
                return 2
            # newline pinned so the report's bytes depend on the measurement and not on the host.
            with open(rp, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(p.stdout)
            reports[tag] = rp
            print("MUTANT analysed label=%s report=%s sha256=%s" % (tag, rp, sha256_of(rp)))

        def judge(cand_tag, neut_tag, what):
            # THE DEGENERATE IDENTITY'S INPUTS ARE HELD FIXED, at the PRISTINE arms, in BOTH
            # orientations. This is not tidiness. The gate reads the identity out of `--degen-static-arm`
            # and `--degen-dyn-arm` ALONE (acceptance.py:759-766) -- `cand`/`neut` never enter it -- so
            # pointing `--degen-static-arm` at the candidate arm, as the pipeline does, would make the
            # mutant orientation compare the BYPASSED kernel's static render against the PRISTINE
            # constructed-cell render and trip `PRB-FAIL-DEGEN-IDENTITY` as well. That code would be an
            # artifact of how the arms were paired here, not of the mutation under control, and a reader
            # could not tell the two apart. Holding the identity's inputs fixed makes the two
            # orientations differ in exactly ONE respect -- the cand/neut pairing -- which is what a
            # control is for; and it is what makes the exactly-one-code assertion below provable rather
            # than optimistic: the degen checks are deterministic on inputs that are byte-identical
            # across the two runs, and the acceptance run has already made them pass.
            cmd = [sys.executable, args.gate,
                   "--criteria", args.criteria,
                   "--plan", os.path.join(dirs[cand_tag], "gh19_s3_plan.tsv"),
                   "--cand-report", reports[cand_tag], "--cand-arm", dirs[cand_tag],
                   "--neut-report", reports[neut_tag], "--neut-arm", dirs[neut_tag],
                   "--degen-static-arm", dirs["probe_A"],
                   "--degen-dyn-arm", dirs["degen_A2"]]
            g = run(cmd)
            f = gate_facts(g.stdout)
            print("MUTANT orientation=%-10s cand=%s neut=%s exit=%d verdict=%s "
                  "refusals=%d fail=%s"
                  % (what, cand_tag, neut_tag, g.returncode, f["verdict"],
                     sum(f["refuse"].values()),
                     ",".join("%s=%d" % kv for kv in sorted(f["fail"].items())) or "-"))
            if g.stderr:
                sys.stderr.write(g.stderr)
            return g.returncode, g.stdout, f

        # The acceptance orientation. This is LEG 1's claim, re-derived here from the same two reports
        # so that the mutant below cannot be explained as "the gate was fed something else".
        ref_rc, ref_out, ref = judge("probe_A", "probe_B", "acceptance")
        if ref_rc != EXIT_PASS:
            sys.stdout.write(ref_out)
            problems.append("the corrected arm did not PASS in the acceptance orientation (exit=%d, "
                            "verdict=%s): a red mutant would then only prove the gate is broken"
                            % (ref_rc, ref["verdict"]))

        mut_rc, mut_out, mut = judge("probe_B", "probe_A", "mutant")
        sys.stdout.write(mut_out)
        if mut_rc == EXIT_REFUSE or mut["refuse"]:
            problems.append("the neutralised arm REFUSED (exit=%d, %d refusal code(s)): the artifacts "
                            "failed an input check, so NO judgement was issued. A refusal is not the "
                            "gate catching a defect and must never be counted as one."
                            % (mut_rc, sum(mut["refuse"].values())))
        elif mut_rc != EXIT_RED:
            problems.append("the neutralised arm exited %d, not the gate's RED (%d)" % (mut_rc, EXIT_RED))
        if mut["verdict"] != "RED":
            problems.append("the neutralised arm's gate reported verdict=%r, not 'RED'" % mut["verdict"])
        if not mut["fail"].get(FAIL_IMPROVEMENT):
            problems.append("the neutralised arm did not name %s: a non-zero exit could be any other "
                            "failure and would not show the improvement columns are the thing that "
                            "rejected it" % FAIL_IMPROVEMENT)
        # Exactly one failing code, not merely "at least the right one". The gate has three FAIL codes
        # and the other two read only the degenerate arms, which are held byte-identical across the two
        # orientations -- so a second code here would mean either that the identity's inputs are no
        # longer independent of the cand/neut pairing (this runner's whole reason for fixing them), or
        # that something other than the improvement rejected the arm. Both are worth failing on.
        others = sorted(k for k in mut["fail"] if k != FAIL_IMPROVEMENT)
        if others:
            problems.append("the neutralised arm's failures were %s; expected exactly [%s]. The other "
                            "code(s) cannot be attributed to the cand/neut swap, which makes the "
                            "attribution of any of them to the improvement ambiguous."
                            % (", ".join(sorted(mut["fail"])), FAIL_IMPROVEMENT))

        if problems:
            print("\nPRB-MUTANT FAILED:")
            for p in problems:
                print("  - %s" % p)
            return 1
        print("\nPRB-MUTANT PASS: the corrected arm passed in the acceptance orientation; the "
              "neutralised arm was rejected BY NAME as %s in the mutant orientation, over the SAME two "
              "reports and without a refusal and without a crash. Separately, the degen-dispatch arm "
              "fired the PREMISE exit bit (%d), not the stimulus bit (%d), with %d measured "
              "source span(s) reported -- PREMISE-LIVE evidence, and NOT a verdict about the identity, "
              "whose falsifiability control is the one-ulp tamper in LEG 2."
              % (FAIL_IMPROVEMENT, bit_premise, bit_stimulus, len(spans)))
        return 0
    finally:
        if args.out is None:
            shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
