#!/usr/bin/env python3
# Copyright (c) 2026 Lunar 24 contributors
# SPDX-License-Identifier: Apache-2.0
# task #120 / GH#19 S6: stage the A/B NEUTRAL ARM's header -- the product's vco.h with the two
# value-jump correction terms removed, and nothing else changed.
#
# WHY THIS EXISTS. S6's equality criterion used to be "the default patch's output is bit-identical
# to the PRE-S6 product, whose committed raw windows were rendered on macOS". That claim is not
# portable: the default patch evaluates `std::sin(kTwoPi * p)` (vco.h:508), Apple's libm and glibc
# disagree on 3.76% of identical arguments (every difference exactly 1 ULP), and the commit-time
# snapshot therefore can never be reproduced bit-for-bit on the CI platform. Measured, not reasoned:
# the criterion read 0 locally and 652 in CI, and a literal pre-S6 tree rendered by the CI compiler
# reproduced the same 652 -- i.e. the gap was the toolchain, not the change (task #120's
# discriminator run; the numbers are in report/2026-09-25-task120-gh19-s6-morph-aa.md).
#
# So the criterion is restated as a SAME-BUILD A/B: within one build, arm A (the product, whose two
# new terms are in force) and arm B (the same source with those two terms neutralised) must agree
# bit-for-bit on the eight default sine-node windows. That is the property the old criterion was
# really asserting -- the two terms contribute nothing at morph = 0.5 -- and it is decidable on any
# platform, because both sides come from one compiler with one set of flags.
#
# WHY A SHADOW HEADER AND NOT A COMPILE-TIME SWITCH IN THE PRODUCT. S0 carries the hard edge "no
# hidden switches": a `#ifdef` inside vco.h would put a build-time configuration branch into the
# shipped DSP, and every future reader of that file would have to reason about a second behaviour
# that no product build ever uses. The shadow variant has no such cost: it is generated HERE, at
# build time, from the tree's own vco.h, and the product header is not touched at all. Nothing is
# vendored either -- a committed copy of the corrected file would be a second encoding of the same
# code, free to drift from the one that ships.
#
# THE ANCHOR MUST OCCUR EXACTLY ONCE, and the two digests are printed on every run. A stale anchor
# would stage a PRISTINE header under the neutral arm's name, both arms would then agree
# trivially, and the A/B would pass while measuring nothing. That degenerate state is refused
# here (non-zero exit fails the build) and again in the gate, which requires the two arms to
# DIFFER on the off-default witness cells before it will judge the equality criterion at all.
#
# Usage (used by CMake; also runnable by hand):
#   python3 tools/stage_gh19_s6_shadow.py --repo-root . --out build/gh19_s6_shadow/neutral
import argparse
import hashlib
import os
import sys

VCO_H = "core/include/lunar24/core/vco.h"

# The product's two application lines, verbatim. This is the whole difference between the arms.
NEUTRAL_ANCHOR = (
    "      if (sw > 0.0) v -= sw * r;   // the saw's jump is DOWNWARD (-2) -> subtract R\n"
    "      if (iw > 0.0) v += iw * r;   // the invSaw's is UPWARD (+2) -> add R\n"
)
# The replacement keeps the OUTER GUARD and the residual call and removes only the two additions to
# `v`. Keeping the guard means the neutral arm still evaluates `sw`, `iw` and `r`: the two arms then
# differ in exactly one respect -- whether the correction reaches the output -- and not in a
# secondary "is this expression evaluated at all" respect that a reader would have to account for.
NEUTRAL_REPLACEMENT = (
    "      // GH#19 S6 A/B NEUTRAL ARM -- generated by tools/stage_gh19_s6_shadow.py into a shadow\n"
    "      // include root. The shipped vco.h is NOT touched: this file exists only so that arm B of\n"
    "      // the same-build A/B differs from arm A in the contribution of the two correction terms\n"
    "      // and in nothing else. See that tool's header for why the criterion is an A/B at all.\n"
    "      (void)r;\n"
)
NEUTRAL_EDITS = ((NEUTRAL_ANCHOR, NEUTRAL_REPLACEMENT),)


def sha256_text(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def stage_neutral(repo_root, shadow_root, edits=NEUTRAL_EDITS, quiet=False):
    """Write the neutralised vco.h under `shadow_root` (repo-relative layout preserved, so the
    shadow root can be put FIRST on an include path and will win for that one header while every
    other header still resolves from core/include). Returns (path, tree_sha, neutral_sha) or None,
    and prints an INVALID line naming the reason when it cannot stage.

    Shared with run_gh19_s6_saw_mutants.py on purpose: the mutant arms are rendered with a shadow
    root of their own, and their neutral arm must be the SAME edit as the product's, or the two
    harnesses would be A/B-ing against different variants of the same claim."""
    src = os.path.join(repo_root, VCO_H)
    if not os.path.exists(src):
        print("INVALID: %s does not exist in %s" % (VCO_H, repo_root))
        return None
    with open(src) as fh:
        text = fh.read()
    staged = text
    for old, new in edits:
        n = staged.count(old)
        if n != 1:
            print("INVALID: the neutralising anchor occurs %d times in %s (expected exactly 1):\n%r"
                  % (n, VCO_H, old))
            return None
        staged = staged.replace(old, new)
    tree_sha, neutral_sha = sha256_text(text), sha256_text(staged)
    if tree_sha == neutral_sha:
        # Unreachable while the anchor is non-empty, but stated rather than assumed: an edit that
        # does not change the header would make arm B the product arm, and the A/B would then be
        # the degenerate identity that passes without measuring anything.
        print("INVALID: the neutralised header is byte-identical to the tree's %s" % VCO_H)
        return None
    dst = os.path.join(shadow_root, VCO_H[len("core/include/"):])
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w") as fh:
        fh.write(staged)
    if not quiet:
        print("S6-SHADOW path=%s anchor_hits=1" % dst)
        print("S6-SHADOW tree_sha256=%s" % tree_sha)
        print("S6-SHADOW neutral_sha256=%s differs=yes" % neutral_sha)
    return dst, tree_sha, neutral_sha


def main(argv):
    ap = argparse.ArgumentParser(description="stage the GH#19 S6 same-build A/B neutral arm header")
    ap.add_argument("--repo-root", default=".", help="repo root holding %s" % VCO_H)
    ap.add_argument("--out", required=True, help="shadow include root to write into")
    args = ap.parse_args(argv)
    if stage_neutral(args.repo_root, args.out) is None:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
